CREATE TABLE T_USER (
  USER_ID DECIMAL(20,0) NOT NULL COMMENT '用户ID',
  USER_NAME VARCHAR(50) NOT NULL COMMENT '用户名称',
  PHONE VARCHAR(20) COMMENT '手机号',
  EMAIL VARCHAR(100) COMMENT '邮箱地址',
  STATUS CHAR(1) DEFAULT '1' COMMENT '状态：1-启用 0-禁用',
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATE_TIME DATETIME COMMENT '更新时间'
) COMMENT='用户信息表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE T_ORDER (
  ORDER_ID DECIMAL(20,0) NOT NULL COMMENT '订单ID',
  USER_ID DECIMAL(20,0) NOT NULL COMMENT '用户ID',
  ORDER_NO VARCHAR(32) NOT NULL COMMENT '订单号',
  AMOUNT DECIMAL(10,2) COMMENT '订单金额',
  ORDER_STATUS CHAR(1) COMMENT '订单状态',
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '下单时间'
) COMMENT='订单表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE T_SYS_LOG (
  LOG_ID DECIMAL(20,0) NOT NULL COMMENT '日志ID',
  LOG_TYPE VARCHAR(30) COMMENT '日志类型',
  LOG_CONTENT VARCHAR(4000) COMMENT '日志内容',
  OPERATOR VARCHAR(50) COMMENT '操作人',
  OP_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间'
) COMMENT='系统操作日志表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE UNIQUE INDEX UK_T_USER_PHONE ON T_USER (PHONE);

CREATE INDEX IDX_T_USER_STATUS ON T_USER (STATUS);

CREATE UNIQUE INDEX UK_T_ORDER_NO ON T_ORDER (ORDER_NO);

CREATE INDEX IDX_T_ORDER_USER_TIME ON T_ORDER (USER_ID, CREATE_TIME);

CREATE INDEX IDX_SYS_LOG_TIME ON T_SYS_LOG (OP_TIME);

