/* ===============================
 * 表名：T_USER_INFO
 * 描述：用户基础信息表
 * =============================== */

-- 1. 创建表
CREATE TABLE T_USER_INFO (
    ID            NUMBER(20)        NOT NULL,
    USER_CODE     VARCHAR2(50)       NOT NULL,
    USER_NAME     VARCHAR2(100),
    PHONE         VARCHAR2(20),
    EMAIL         VARCHAR2(100),
    STATUS        CHAR(1)            DEFAULT '1' NOT NULL,
    CREATE_TIME   DATE               DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME   DATE
);

-- 2. 表注释
COMMENT ON TABLE T_USER_INFO IS '用户基础信息表';

-- 3. 字段注释
COMMENT ON COLUMN T_USER_INFO.ID IS '主键ID';
COMMENT ON COLUMN T_USER_INFO.USER_CODE IS '用户编码';
COMMENT ON COLUMN T_USER_INFO.USER_NAME IS '用户名称';
COMMENT ON COLUMN T_USER_INFO.PHONE IS '手机号';
COMMENT ON COLUMN T_USER_INFO.EMAIL IS '邮箱';
COMMENT ON COLUMN T_USER_INFO.STATUS IS '状态：1-正常，0-停用';
COMMENT ON COLUMN T_USER_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_USER_INFO.UPDATE_TIME IS '更新时间';

-- 4. 主键约束
ALTER TABLE T_USER_INFO
ADD CONSTRAINT PK_T_USER_INFO
PRIMARY KEY (ID);

-- 5. 唯一索引（用户编码）
ALTER TABLE T_USER_INFO
ADD CONSTRAINT UK_T_USER_INFO_USER_CODE
UNIQUE (USER_CODE);

-- 6. 普通索引
CREATE INDEX IDX_T_USER_INFO_PHONE
ON T_USER_INFO (PHONE);

CREATE INDEX IDX_T_USER_INFO_CREATE_TIME
ON T_USER_INFO (CREATE_TIME);
