CREATE TABLE T_USER_INFO (
  ID DECIMAL(20,0) NOT NULL COMMENT '主键ID',
  USER_CODE VARCHAR(50) NOT NULL COMMENT '用户编码',
  USER_NAME VARCHAR(100) COMMENT '用户名称',
  PHONE VARCHAR(20) COMMENT '手机号',
  EMAIL VARCHAR(100) COMMENT '邮箱',
  STATUS CHAR(1) NOT NULL DEFAULT '1' COMMENT '状态：1-正常，0-停用',
  CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATE_TIME DATETIME COMMENT '更新时间',
  CONSTRAINT PK_T_USER_INFO PRIMARY KEY (ID),
  CONSTRAINT UK_T_USER_INFO_USER_CODE UNIQUE (USER_CODE)
) COMMENT='用户基础信息表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_T_USER_INFO_PHONE ON T_USER_INFO (PHONE);

CREATE INDEX IDX_T_USER_INFO_CREATE_TIME ON T_USER_INFO (CREATE_TIME);

