-- 测试 INSERT ALL
INSERT ALL
    INTO T_USER (USER_ID, USERNAME) VALUES (1, 'test1')
    INTO T_USER (USER_ID, USERNAME) VALUES (2, 'test2')
SELECT * FROM DUAL;

-- 测试 SELECT FROM DUAL
SELECT SYSDATE FROM DUAL;

SELECT USER, SYSDATE FROM DUAL;
