CREATE TABLE IF NOT EXISTS EMPLOYEES (
  EMP_ID BIGINT NOT NULL COMMENT '员工唯一标识，主键',
  FIRST_NAME VARCHAR(50) COMMENT '员工名',
  LAST_NAME VARCHAR(50) NOT NULL COMMENT '员工姓',
  EMAIL VARCHAR(100) COMMENT '电子邮箱地址',
  HIRE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '入职日期',
  SALARY  DEFAULT 0 COMMENT '月薪',
  STATUS CHAR(1) DEFAULT '1' COMMENT '账号状态(1有效/0禁用)',
  CREATE_TIME DATETIME DEFAULT 'CURRENT_TIMESTAMP' COMMENT '记录创建时间',
  CONSTRAINT PK_EMPLOYEES_pk PRIMARY KEY (EMP_ID)
) COMMENT='员工基本信息表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


CREATE INDEX IDX_EMP_EMAIL_idx ON EMPLOYEES (EMAIL);


CREATE INDEX IDX_EMP_HIRE_DATE_idx ON EMPLOYEES (HIRE_DATE);


