-- 1. 建表
CREATE TABLE T_USER (
    USER_ID        NUMBER(20)      NOT NULL,
    USER_NAME      VARCHAR2(50)     NOT NULL,
    PHONE          VARCHAR2(20),
    EMAIL          VARCHAR2(100),
    STATUS         CHAR(1)          DEFAULT '1',
    CREATE_TIME    DATE             DEFAULT SYSDATE,
    UPDATE_TIME    DATE
);

-- 2. 主键
ALTER TABLE T_USER
ADD CONSTRAINT PK_T_USER PRIMARY KEY (USER_ID);

-- 3. 表注释
COMMENT ON TABLE T_USER IS '用户信息表';

-- 4. 字段注释
COMMENT ON COLUMN T_USER.USER_ID     IS '用户ID';
COMMENT ON COLUMN T_USER.USER_NAME   IS '用户名称';
COMMENT ON COLUMN T_USER.PHONE       IS '手机号';
COMMENT ON COLUMN T_USER.EMAIL       IS '邮箱地址';
COMMENT ON COLUMN T_USER.STATUS      IS '状态：1-启用 0-禁用';
COMMENT ON COLUMN T_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_USER.UPDATE_TIME IS '更新时间';

-- 5. 索引
CREATE UNIQUE INDEX UK_T_USER_PHONE ON T_USER (PHONE);
CREATE INDEX IDX_T_USER_STATUS ON T_USER (STATUS);


CREATE TABLE T_ORDER (
    ORDER_ID      NUMBER(20)    NOT NULL,
    USER_ID       NUMBER(20)    NOT NULL,
    ORDER_NO      VARCHAR2(32)  NOT NULL,
    AMOUNT        NUMBER(10,2),
    ORDER_STATUS  CHAR(1),
    CREATE_TIME   DATE          DEFAULT SYSDATE
);

ALTER TABLE T_ORDER
ADD CONSTRAINT PK_T_ORDER PRIMARY KEY (ORDER_ID);

ALTER TABLE T_ORDER
ADD CONSTRAINT FK_T_ORDER_USER
FOREIGN KEY (USER_ID) REFERENCES T_USER (USER_ID);

COMMENT ON TABLE T_ORDER IS '订单表';

COMMENT ON COLUMN T_ORDER.ORDER_ID     IS '订单ID';
COMMENT ON COLUMN T_ORDER.USER_ID      IS '用户ID';
COMMENT ON COLUMN T_ORDER.ORDER_NO     IS '订单号';
COMMENT ON COLUMN T_ORDER.AMOUNT       IS '订单金额';
COMMENT ON COLUMN T_ORDER.ORDER_STATUS IS '订单状态';
COMMENT ON COLUMN T_ORDER.CREATE_TIME  IS '下单时间';

-- 常见查询联合索引
CREATE UNIQUE INDEX UK_T_ORDER_NO ON T_ORDER (ORDER_NO);
CREATE INDEX IDX_T_ORDER_USER_TIME ON T_ORDER (USER_ID, CREATE_TIME);


CREATE TABLE T_SYS_LOG (
    LOG_ID       NUMBER(20)    NOT NULL,
    LOG_TYPE     VARCHAR2(30),
    LOG_CONTENT  VARCHAR2(4000),
    OPERATOR     VARCHAR2(50),
    OP_TIME      DATE          DEFAULT SYSDATE
);

ALTER TABLE T_SYS_LOG
ADD CONSTRAINT PK_T_SYS_LOG PRIMARY KEY (LOG_ID);

COMMENT ON TABLE T_SYS_LOG IS '系统操作日志表';

COMMENT ON COLUMN T_SYS_LOG.LOG_ID      IS '日志ID';
COMMENT ON COLUMN T_SYS_LOG.LOG_TYPE    IS '日志类型';
COMMENT ON COLUMN T_SYS_LOG.LOG_CONTENT IS '日志内容';
COMMENT ON COLUMN T_SYS_LOG.OPERATOR    IS '操作人';
COMMENT ON COLUMN T_SYS_LOG.OP_TIME     IS '操作时间';

-- 时间查询索引
CREATE INDEX IDX_SYS_LOG_TIME ON T_SYS_LOG (OP_TIME);
